/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.corpus.jsonc --include-runtime=false --strict-vars=false --env-interface=ResearchCorpusBindings research-corpus-configuration.d.ts` (hash: c31b0b2f1169c0144a0ea574986c0396)
interface __BaseEnv_ResearchCorpusBindings {
	PAPERS: R2Bucket;
	ARTIFACT_ANALYSIS_QUEUE: Queue;
	AUTH_MODE: string;
	ACCESS_TEAM_DOMAIN: string;
	ACCESS_AUD: string;
	CORPUS_ALLOWED_ORIGINS: string;
	REFERENCE_LIBRARIES: DurableObjectNamespace /* ReferenceLibrary from kirjolab */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/research-corpus/worker");
	}
	interface Env extends __BaseEnv_ResearchCorpusBindings {}
}
interface ResearchCorpusBindings extends __BaseEnv_ResearchCorpusBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUTH_MODE" | "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD" | "CORPUS_ALLOWED_ORIGINS">> {}
}
