export const exampleRoutes = [
  { path: "/", purpose: "Recent scholarly work dashboard" },
  { path: "/library", purpose: "Project-free private reference library" },
  { path: "/library/pdfs/:id", purpose: "Routable private library PDF reader" },
  { path: "/editor", purpose: "Resume a writing project" },
  { path: "/editor/:id", purpose: "Stable writing-project editor" },
  { path: "/review", purpose: "Evidence review catalog" },
  { path: "/review/:id", purpose: "Independent collaborative evidence review" },
  { path: "/workspaces/:id", purpose: "Legacy writing-project redirect" },
  { path: "/share/:token", purpose: "Read-only workspace link" },
  { path: "/edit/:token", purpose: "Editable workspace link" },
  { path: "/api/workspaces", purpose: "Workspace catalog" },
  { path: "/api/workspaces/demo", purpose: "Portable workspace resource" },
  { path: "/api/reviews", purpose: "Independent review catalog" },
  { path: "/api/reviews/:id", purpose: "Independent review resource" },
  { path: "/api/session", purpose: "Authenticated identity" },
  { path: "/api/health", purpose: "JSON health endpoint for tooling and smoke tests" },
];
